# Model
feature_type: "raft"
extraction_fps: null # For original video fps, leave as "null" (None)
extraction_total: null # extract a fix number of frames. It is mutually exclusive with "fps"
side_size: null # if resized to the smaller edge, min(W, H) = side_size, if to the larger: max(W, H), if "null" (None) no resize is performed
resize_to_smaller_edge: true # if false, the larger edge will be used to be resized to `side_size`
finetuned_on: "sintel" # also 'kitti' is supported

# Extraction Parameters
device: "cuda:0" # device as in `torch`, can be 'cpu'
batch_size: 1 # increase the extraction speed with batching
on_extraction: "print" # what to do once the features are extracted. Can be ['print', 'save_numpy', 'save_pickle']
output_path: "./output" # where to store results if saved
tmp_path: "./tmp" # folder to store the temporary files used for extraction (frames or aud files)
keep_tmp_files: false # to keep temp files after feature extraction.
show_pred: false # to show preds of a model, i.e. on a pre-train dataset for each feature (Kinetics 400)

# config
config: null

# submitit
slurm:
  submit: false
  name: "VidFeats"
  log_folder_path: "./output"
  num_arrays: 2
  max_arrays: 10 # Max num arrays to run
  mem_gb: 50 # Memory per task in GB
  cpus_per_task: 10 # CPU cores to use per task
  timeout_hrs: 1 # Job length in hours
  partition: "gpu"
  monitor: true

# Video paths
video_paths: null
file_with_video_paths: null # if the list of videos is large, you might put them in a txt file, use this argument to specify the path
