# Model
feature_type: 's3d'
stack_size: 64 # Feature time span in fps
step_size: 64 # Feature step size in fps
extraction_fps: 25 # 25 is my best guess. For original video fps, leave unspecified "null" (None)

# Extraction Parameters
device: 'cuda:0'  # device as in `torch`, can be 'cpu'
on_extraction: 'print'  # what to do once the features are extracted. Can be ['print', 'save_numpy', 'save_pickle']
output_path: './output' # where to store results if saved
tmp_path: './tmp' # folder to store the temporary files used for extraction (frames or aud files)
keep_tmp_files: false # to keep temp files after feature extraction.
show_pred: false # to show preds of a model, i.e. on a pre-train dataset for each feature (Kinetics 400)

# config
config: null

# Video paths
video_paths: null
file_with_video_paths: null # if the list of videos is large, you might put them in a txt file, use this argument to specify the path
